# Generated by Django 5.2.15 on 2026-06-30 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict, help_text='{to, type, body, media_id, ...}')),
                ('run_at', models.DateTimeField(db_index=True)),
                ('recurrence', models.CharField(blank=True, help_text='iCal RRULE for recurring sends (optional)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='devices.device')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['run_at'],
                'indexes': [models.Index(fields=['status', 'run_at'], name='scheduler_s_status_41343f_idx')],
            },
        ),
    ]
