# Generated by Django 5.2.15 on 2026-06-30 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initializing', 'Initializing'), ('qr', 'Awaiting QR scan'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed'), ('logged_out', 'Logged out')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('wwebjs', 'whatsapp-web.js'), ('baileys', 'Baileys')], default='wwebjs', max_length=20)),
                ('worker_id', models.CharField(blank=True, max_length=128)),
                ('session_ref', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_device_name_per_workspace')],
            },
        ),
    ]
