# Generated by Django 5.2.15 on 2026-06-30 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('starts_with', 'Starts with'), ('regex', 'Regex')], default='contains', max_length=12)),
                ('pattern', models.CharField(max_length=512)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('response_body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher numbers are evaluated first.')),
                ('device', models.ForeignKey(blank=True, help_text='Leave empty to apply to all devices in the workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to='devices.device')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
